### ISSUE TITLE
The resolution

### ISSUE THREAD

**Issue by Halfshadow** [RavenDS/dex-editor#2]
The resolution is too high for this tool and without a 4K monitor I can't use all the buttons, but only a part. And didn't work then to do my edits, 'cause I can't not even scroll the window to reach the not visibile part. Not even the resizing is allowed.

**Comment by RavenDS** [comment]
GUI has been resized in [version 1.3.3](https://github.com/RavenDS/dex-editor/releases/latest) to accomodate for 1920x1080 screens. Resolutions under 1080p are currently unsupported.
