### ISSUE TITLE
Special Indoor D/P/Pt issues and resolution

### ISSUE THREAD

**Issue by Halfshadow** [RavenDS/dex-editor#3]
With D/P/Platinum still cannot edit the indoor special areas, opening the original ones (as example Loudred in Mt. Coronet) semms that he hasn't a special area to appear, and instead yes.

The outdoor special areas editing worked almost fine in 1.3.2. version but the indoor instead not.

And the resolution of the GUI is too big for a 1600x900 screen like a notebook, you could at least offer the option to adjust the window and scroll it if you want to keep that resolution, with 1.3.2. I could use it changing the screen orientation to vertical (also if is very tedious) but with the 1.3.3 instead not, 'cause if I change the orientation the window get worse when I try to move it to see all the elements.

But could you please at least adjust the indoor special area modding for D/P/Pt?

**Comment by Halfshadow** [comment]
I discovered what happens.
In 1.3.2. with Platinum the special outdoors locations are edited correctly, the indoors instead use wrong subfiles in the temp folder of the splitted zukan_enc.

Then as example if a pokémon have a 2980 subfile in your tool to edit the indoor special location, instead have to be subtracted 1980 subfiles to find the right one instead and then instead of 2980 is 1000.

In this way finally I fixed my project simply replacing the subfiles in the temp folder and then exporting the zukan_enc.

Using the 1.3.2 version. Would be cute if you could write a version with this issue fixed and to works with a screen resolutions of 1600x900 too as example...

**Comment by ravenDS** [comment]
[Fixed in v1.4](https://github.com/RavenDS/dex-editor/releases/latest)

Thanks for reporting
